hazelcast:
  backup-count: 1
  time-to-live-seconds: 3600
  domain-package: org.ironforge.base.domain.*
  management-center:
    enabled: false
    update-interval: 3
    url: http://localhost:8180/mancenter
spring:
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        hostname: ${spring.cloud.client.ip-address}
        instance-id: ${spring.application.name}-${spring.cloud.client.ip-address}-${server.port}
  jackson:
    property-naming-strategy: CAMEL_CASE_TO_LOWER_CASE_WITH_UNDERSCORES
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/oauth2
    driver-class-name: org.postgresql.Driver
    username: oauth2
    password: oauth2
  flyway:
    url: ${spring.datasource.url}
    password: ${spring.datasource.password}
    user: ${spring.datasource.username}
  sleuth:
    baggage-keys:
      - req-id
      - prefer-version-tag
    propagation-keys:
      - user-id
      - user-name
      - merchant-id
      - merchant-name
      - req-id
      - token
    log:
      slf4j:
        whitelisted-mdc-keys:
          - user-id
          - req-id
  jpa:
    database: POSTGRESQL
    show-sql: true
    properties:
      hibernate.id.new_generator_mappings: true
      hibernate.connection.provider_disables_autocommit: true
      hibernate.cache.use_second_level_cache: true
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false
      hibernate.cache.region.factory_class: com.hazelcast.hibernate.HazelcastCacheRegionFactory
      hibernate.cache.hazelcast.instance_name: ${spring.application.name}
      hibernate.cache.use_minimal_puts: true
      hibernate.cache.hazelcast.use_lite_member: true
feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true
  hystrix:
    enabled: true